// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "74845eb5-c783-4af0-ba37-b7d04b2b9c3f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedAccesoChange();

int uptime;
bool led_acceso;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(uptime, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(led_acceso, READWRITE, ON_CHANGE, onLedAccesoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
